"""smarter like table setup

Revision ID: aaa58a3f2e65
Revises: 2c2a1826f5d0
Create Date: 2018-08-20 15:45:45.147534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaa58a3f2e65'
down_revision = '96daae59325b'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vanity_userlikes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name=op.f('fk_vanity_userlikes_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vanity_userlikes'))
    )
    op.create_table('vanity_postlikes',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_like_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_vanity_postlikes_post_id_posts')),
    sa.ForeignKeyConstraint(['user_like_id'], ['vanity_userlikes.id'], name=op.f('fk_vanity_postlikes_user_like_id_vanity_userlikes')),
    sa.PrimaryKeyConstraint('post_id', 'user_like_id', name=op.f('pk_vanity_postlikes'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vanity_postlikes')
    op.drop_table('vanity_userlikes')
    # ### end Alembic commands ###
