"""smarter like table setup

Revision ID: 6e48e69ed9ac
Revises: 2c2a1826f5d0
Create Date: 2018-08-20 17:13:32.048895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e48e69ed9ac'
down_revision = '96daae59325b'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vanity_postlikes',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_vanity_postlikes_post_id_posts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_vanity_postlikes_user_id_users')),
    sa.PrimaryKeyConstraint('post_id', 'user_id', name=op.f('pk_vanity_postlikes'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vanity_postlikes')
    # ### end Alembic commands ###
